/**
 * GLSL 语言的 Monaco Monarch tokens provider
 * 提供高亮 / 大纲能力（不参与编译，只为编辑器视觉）
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function registerGLSLLanguage(monaco: any) {
  if (
    !monaco.languages
      .getLanguages()
      .some((l: { id: string }) => l.id === "glsl")
  ) {
    monaco.languages.register({ id: "glsl" });
    monaco.languages.setMonarchTokensProvider("glsl", {
      keywords: [
        "attribute",
        "const",
        "uniform",
        "varying",
        "break",
        "continue",
        "do",
        "for",
        "while",
        "if",
        "else",
        "in",
        "out",
        "inout",
        "true",
        "false",
        "lowp",
        "mediump",
        "highp",
        "precision",
        "invariant",
        "discard",
        "return",
        "mat2",
        "mat3",
        "mat4",
        "vec2",
        "vec3",
        "vec4",
        "ivec2",
        "ivec3",
        "ivec4",
        "bvec2",
        "bvec3",
        "bvec4",
        "sampler2D",
        "samplerCube",
        "void",
        "struct",
      ],
      builtins: [
        "gl_Position",
        "gl_FragColor",
        "gl_FragCoord",
        "gl_PointSize",
        "gl_FrontFacing",
        "gl_PointCoord",
        "sin",
        "cos",
        "tan",
        "asin",
        "acos",
        "atan",
        "pow",
        "exp",
        "log",
        "sqrt",
        "inversesqrt",
        "abs",
        "sign",
        "floor",
        "ceil",
        "fract",
        "mod",
        "min",
        "max",
        "clamp",
        "mix",
        "step",
        "smoothstep",
        "length",
        "distance",
        "dot",
        "cross",
        "normalize",
        "reflect",
        "refract",
        "texture",
        "texture2D",
        "textureCube",
        "radians",
        "degrees",
      ],
      tokenizer: {
        root: [
          [/\/\/.*$/, "comment"],
          [/\/\*/, "comment", "@comment"],
          [/\b(?:void|bool|int|float|vec[234]|ivec[234]|mat[234])\b/, "type"],
          [/\b\w+(?=\s*\()/, "function"],
          [/[0-9]+\.[0-9]+/, "number.float"],
          [/\.[0-9]+/, "number.float"],
          [/[0-9]+/, "number"],
          [/"([^"\\]|\\.)*$/, "string.invalid"],
          [/"/, "string", "@string"],
        ],
        comment: [
          [/[^/*]+/, "comment"],
          [/\*\//, "comment", "@pop"],
          [/[/*]/, "comment"],
        ],
        string: [
          [/[^\\"]+/, "string"],
          [/\\./, "string.escape"],
          [/"/, "string", "@pop"],
        ],
      },
    });
  }
}
